name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'mobile/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'mobile/**' ]

jobs:
  flutter_checks:
    name: Flutter Code Quality Checks
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Check formatting
        run: flutter format --set-exit-if-changed lib/ test/

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: mobile/coverage/lcov.info
          flags: flutter
          name: flutter-coverage

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Build iOS (no-codesign)
        run: flutter build ios --no-codesign
        if: runner.os == 'macOS'